# Syntax reference for this file:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: BuildTest
on: [push]

# https://gist.github.com/c-bata/ed5e7b7f8015502ee5092a3e77937c99
jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-python
      # ^-- This gives info on matrix testing.
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # I don't know where the "run" thing is documented.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/test-requires.txt
          pip install .
      - name: Build Generic Sphinx docs
        if: success()
        working-directory: ./tests/generic_sphinx
        run: sphinx-build -b docbook source build
      - name: Build Autodoc Sphinx docs
        if: success()
        working-directory: ./tests/autodoc_validation
        run: sphinx-build -b docbook source build
      - name: Build SphinxArg Sphinx docs
        if: success()
        working-directory: ./tests/sphinxarg_validation
        run: sphinx-build -b docbook source build
